stages:
  - containerization
  - deployment

variables:
  DOCKER_IMAGE: 172.16.98.151:5000/application_forms_manager
  DEPLOYMENT: afm-deployment

containerization:
  stage: containerization
  script:
    - echo ${NEO4J_USERNAME}
    - echo "exports.neo4j = { username: '${NEO4J_USERNAME}', password: '${NEO4J_PASSWORD}', }"
    - echo "exports.session = { secret: '${SESSION_SECRET}'}"
    - docker build -t ${DOCKER_IMAGE} .
    - docker push ${DOCKER_IMAGE}

deployment:
  stage: deployment
  script:
    - kubectl apply -f deployment.yml
    - kubectl rollout restart deployment/${DEPLOYMENT}
  environment:
    name: staging
