stages:
  - containerization
  - deployment

variables:
  DOCKER_IMAGE: 172.16.98.151:5000/application_forms_manager
  DEPLOYMENT: afm-deployment

containerization:
  stage: containerization
  script:
    - docker build -t ${DOCKER_IMAGE} .
    - docker push ${DOCKER_IMAGE}

deployment:
  stage: deployment
  script:
    - kubectl apply -f deployment.yml
    - kubectl rollout restart deployment/${DEPLOYMENT}
  environment:
    name: staging
