stages:
  - containerization
  - deployment

variables:
  APPLICATION_NAME: shinsei-manager
  DOCKER_IMAGE: ${CONTAINER_REGISTRY}/${APPLICATION_NAME} # Docker registry is obtained from the GitLab runner

containerization:
  stage: containerization
  script:
    - cp ${ENV} ./.env
    - >
      docker build
      --build-arg HTTP_PROXY=$HTTP_PROXY
      --build-arg HTTPS_PROXY=$HTTPS_PROXY
      -t ${DOCKER_IMAGE}
      .
    - docker push ${DOCKER_IMAGE}
    - docker image rm ${DOCKER_IMAGE} # Cleanup

deployment:
  stage: deployment
  script:
    - envsubst < deployment.yml | kubectl apply -f -
    - kubectl rollout restart deployment/${APPLICATION_NAME}
    # If a nodeport is specified, serve app through a nodeport service
    - if [ -z ${SERVICE_PORT} ]; then echo "SERVICE_PORT not set"; else - envsubst < nodeport_service.yml | kubectl apply -f -; fi
    # if a domain name is specified, serve app through an ingress
    # - [[ -z ${CERTIFICATE_DOMAIN}]] || - envsubst < ingress.yml | kubectl apply -f -
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE}
