apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APPLICATION_NAME}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      volumes:
      - name: ${APPLICATION_NAME}
        persistentVolumeClaim:
          claimName: ${APPLICATION_NAME}
      containers:
      - name: ${APPLICATION_NAME}
        image: ${CONTAINER_REGISTRY}/${APPLICATION_NAME}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/pv"
          name: ${APPLICATION_NAME}
      imagePullSecrets:
      - name: registry-credentials # Credentials to pull image from registry
---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  ports:
  - port: 80
    nodePort: ${SERVICE_PORT}
  selector:
    app: ${APPLICATION_NAME}
  type: NodePort
