apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      # volumes:
      #   - name: ${APPLICATION_NAME}
      #     persistentVolumeClaim:
      #       claimName: ${APPLICATION_NAME}
      containers:
        - name: ${APPLICATION_NAME}
          image: ${CONTAINER_IMAGE_TAGGED}
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: environment-variables
          env:
            - name: IDENTIFICATION_URL
              value: http://employee-manager/v3/users/self
            - name: S3_BUCKET
              value: approval-workflow-attachments
          # volumeMounts:
          #   - mountPath: "/usr/share/pv"
          #     name: ${APPLICATION_NAME}
