apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APPLICATION_NAME}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${PVC_STORAGE}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      volumes:
      - name: ${APPLICATION_NAME}
        persistentVolumeClaim:
          claimName: ${APPLICATION_NAME}
      containers:
      - name: ${APPLICATION_NAME}
        image: ${DOCKER_IMAGE}
        # Pull new images on restart
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        # Get environment variables from K8s
        envFrom:
        - secretRef:
           name: environment-variables
        # Mount storage to the PVC
        volumeMounts:
        - mountPath: "/usr/share/pv"
          name: ${APPLICATION_NAME}
      # Login to the registry to pull the image
      imagePullSecrets:
      - name: registry-credentials
