apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APPLICATION_NAME}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${PVC_STORAGE}
